CREATE TABLE T_SAV_CLIENTE (
    ID_SAV_CLIENTE INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    ESTADO_CIVIL VARCHAR(50) NOT NULL,
    SEXO CHAR(1) CONSTRAINT CK_T_SAV_SEXO_CLIENTE CHECK(SEXO IN('M','F','I')),
    RENDA DECIMAL(10, 2) NOT NULL,
    PROFISSAO VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_CADASTRO_CLIENTE (
    ID_SAV_CADASTRO_CLIENTE INT NOT NULL,
    PRIMARY KEY(ID_SAV_CADASTRO_CLIENTE),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE4 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE),
    ID_SAV_DOCUMENTOS INT CONSTRAINT FK_ID_SAV_DOCUMENTOS REFERENCES T_SAV_DOCUMENTOS(ID_SAV_DOCUMENTOS),
    ID_SAV_ENDERECO INT CONSTRAINT FK_ID_SAV_ENDERECO REFERENCES T_SAV_ENDERECO(ID_SAV_ENDERECO),
    ID_SAV_CONTATO INT CONSTRAINT DK_ID_SAV_CONTATO REFERENCES T_SAV_CONTATO(ID_SAV_CONTATO)
);

CREATE TABLE T_SAV_DOCUMENTOS (
    ID_SAV_DOCUMENTOS INT NOT NULL,
    RG NUMERIC (9) NOT NULL UNIQUE,
    CPF NUMERIC (11) NOT NULL UNIQUE,
    CNH NUMERIC (10) NOT NULL UNIQUE,
    PRIMARY KEY(ID_SAV_DOCUMENTOS),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_ENDERECO (
    ID_SAV_ENDERECO INT NOT NULL,
    CEP NUMERIC(9) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NR_NUMERO INT NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_SAV_ENDERECO),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE2 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_CONTATO (
    ID_SAV_CONTATO INT NOT NULL,
    TELEFONE_RESIDENCIAL NUMERIC(15),
    TELEFONE_CELULAR NUMERIC(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_SAV_CONTATO),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE3 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_SEGURO (
    ID_SAV_SEGURO INT NOT NULL,
    PRIMARY KEY(ID_SAV_SEGURO),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE5 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_SEGURO_PEDAL_LEVE (
    ID_SAV_SEGURO_PEDAL_LEVE INT NOT NULL,
    VL_SEGURO DECIMAL(10,2),
    DS_COBERTURAS VARCHAR(255),
    PRIMARY KEY(ID_SAV_SEGURO_PEDAL_LEVE),
    ID_SAV_SEGURO INT CONSTRAINT FK_ID_SAV_SEGURO REFERENCES T_SAV_SEGURO(ID_SAV_SEGURO)
);

CREATE TABLE T_SAV_SEGURO_PEDAL_ESSENCIAL (
    ID_SAV_SEGURO_PEDAL_ESSENCIAL INT NOT NULL,
    VL_SEGURO DECIMAL(10,2),
    DS_COBERTURAS VARCHAR(255),
    PRIMARY KEY(ID_SAV_SEGURO_PEDAL_ESSENCIAL),
    ID_SAV_SEGURO INT CONSTRAINT FK_ID_SAV_SEGURO2 REFERENCES T_SAV_SEGURO(ID_SAV_SEGURO)
);

CREATE TABLE T_SAV_SEGURO_PEDAL_ELITE (
    ID_SAV_SEGURO_PEDAL_ELITE INT NOT NULL,
    VL_SEGURO DECIMAL(10,2),
    DS_COBERTURAS VARCHAR(255),
    PRIMARY KEY(ID_SAV_SEGURO_PEDAL_ELITE),
    ID_SAV_SEGURO INT CONSTRAINT FK_ID_SAV_SEGURO3 REFERENCES T_SAV_SEGURO(ID_SAV_SEGURO)
);

CREATE TABLE T_SAV_PIX (
    ID_SAV_PIX INT NOT NULL,
    DT_TRANSACAO DATE NOT NULL,
    NR_TRANSACAO NUMERIC(9) NOT NULL UNIQUE,
    PRIMARY KEY(ID_SAV_PIX),
    ID_SAV_PAGAMENTO INT CONSTRAINT FK_ID_SAV_PAGAMENTO REFERENCES T_SAV_PAGAMENTO(ID_SAV_PAGAMENTO)
);

CREATE TABLE T_SAV_BOLETO (
    ID_SAV_BOLETO INT NOT NULL,
    DT_TRANSACAO DATE NOT NULL,
    NR_BOLETO NUMERIC NOT NULL UNIQUE,
    PRIMARY KEY(ID_SAV_BOLETO),
    ID_SAV_PAGAMENTO INT CONSTRAINT FK_ID_SAV_PAGAMENTO2 REFERENCES T_SAV_PAGAMENTO(ID_SAV_PAGAMENTO)
);

CREATE TABLE T_SAV_CARTAO_CREDITO (
    ID_SAV_CARTAO_CREDITO INT NOT NULL,
    NR_CARTAO NUMERIC(16) NOT NULL UNIQUE,
    NM_CARTAO VARCHAR(255) NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    CODIGO_SEGURANCA NUMERIC(3) NOT NULL,
    NR_AGENCIA NUMERIC(10) NOT NULL,
    NR_CONTA NUMERIC(10) NOT NULL,
    NM_BANCO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_SAV_CARTAO_CREDITO),
    ID_SAV_PAGAMENTO INT CONSTRAINT FK_ID_SAV_PAGAMENTO3 REFERENCES T_SAV_PAGAMENTO(ID_SAV_PAGAMENTO)
);

CREATE TABLE T_SAV_CARTAO_DEBITO (
    ID_SAV_CARTAO_DEBITO INT NOT NULL,
    NR_CARTAO NUMERIC(16) NOT NULL UNIQUE,
    NM_CARTAO VARCHAR(255) NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    CODIGO_SEGURANCA NUMERIC(3) NOT NULL,
    NR_AGENCIA NUMERIC(10) NOT NULL,
    NR_CONTA NUMERIC(10) NOT NULL,
    NM_BANCO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_SAV_CARTAO_DEBITO),
    ID_SAV_PAGAMENTO INT CONSTRAINT FK_ID_SAV_PAGAMENTO4 REFERENCES T_SAV_PAGAMENTO(ID_SAV_PAGAMENTO)
);

CREATE TABLE T_SAV_PAGAMENTO (
    ID_SAV_PAGAMENTO INT NOT NULL,
    PRIMARY KEY(ID_SAV_PAGAMENTO),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE6 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_CLIENTE_PORTO (
    ID_SAV_CLIENTE_PORTO INT NOT NULL,
    VOUCHER_DESCONTO NUMERIC(20),
    VL_DESCONTO DECIMAL(10, 2),
    DT_VALIDADE DATE,
    PRIMARY KEY (ID_SAV_CLIENTE_PORTO),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE7 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_VISTORIA (
    ID_SAV_VISTORIA INT NOT NULL,
    DT_VISTORIA DATE,
    LISTA_VISTORIA VARCHAR(100),
    PRIMARY KEY (ID_SAV_VISTORIA),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE8 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE)
);

CREATE TABLE T_SAV_CADASTRO_BICICLETA (
    ID_SAV_CADASTRO_BICICLETA INT NOT NULL,
    DS_MARCA VARCHAR(20),
    DS_COR VARCHAR(20),
    DT_ANO DATE,
    DS_VALOR DECIMAL(10, 2),
    NT_FISCAL VARCHAR(20),
    PRIMARY KEY(ID_SAV_CADASTRO_BICICLETA),
    ID_SAV_CLIENTE INTEGER CONSTRAINT FK_ID_SAV_CLIENTE9 REFERENCES T_SAV_CLIENTE(ID_SAV_CLIENTE),
    ID_SAV_MODALIDADE INT CONSTRAINT FK_ID_SAV_MODALIDADE REFERENCES T_SAV_MODALIDADE(ID_SAV_MODALIDADE),
    ID_SAV_ITENS_CUSTOMIZADOS INT CONSTRAINT FK_ID_SAV_ITENS_CUSTOMIZADOS REFERENCES T_SAV_ITENS_CUSTOMIZADOS(ID_SAV_ITENS_CUSTOMIZADOS)
);

CREATE TABLE T_SAV_MODALIDADE (
    ID_SAV_MODALIDADE INT NOT NULL,
    PRIMARY KEY (ID_SAV_MODALIDADE),
    ID_SAV_MOUNTAIN_BIKE INT CONSTRAINT FK_ID_SAV_MOUNTAIN_BIKE REFERENCES T_SAV_MOUNTAIN_BIKE(ID_SAV_MOUNTAIN_BIKE),
    ID_PERFORMANCE INT CONSTRAINT FK_ID_SAV_PERFORMANCE REFERENCES T_SAV_PERFORMANCE(ID_SAV_PERFORMANCE),
    ID_URBANA INT CONSTRAINT FK_ID_SAV_URBANA REFERENCES T_SAV_URBANA(ID_SAV_URBANA)
);

CREATE TABLE T_SAV_ITENS_CUSTOMIZADOS (
    ID_SAV_ITENS_CUSTOMIZADOS INT NOT NULL,
    NM_ITEM VARCHAR(50),
    DS_ITEM VARCHAR(50),
    VL_ITEM DECIMAL(10,2),
    PRIMARY KEY (ID_SAV_ITENS_CUSTOMIZADOS)
);

CREATE TABLE T_SAV_MOUNTAIN_BIKE (
    ID_SAV_MOUNTAIN_BIKE INT NOT NULL,
    DS_BIKE VARCHAR(50),
    DS_FINALIDADE_BIKE VARCHAR(50),
    PRIMARY KEY (ID_SAV_MOUNTAIN_BIKE)
);

CREATE TABLE T_SAV_PERFORMANCE (
    ID_SAV_PERFORMANCE INT NOT NULL,
    DS_BIKE VARCHAR(50),
    DS_FINALIDADE_BIKE VARCHAR(50),
    PRIMARY KEY (ID_SAV_PERFORMANCE)
);

CREATE TABLE T_SAV_URBANA (
    ID_SAV_URBANA INT NOT NULL,
    DS_BIKE VARCHAR(50),
    DS_FINALIDADE_BIKE VARCHAR(50),
    PRIMARY KEY (ID_SAV_URBANA)
);


DROP TABLE T_SAV_CLIENTE; /* CRIADO 1 */
DROP TABLE T_SAV_CADASTRO_CLIENTE; /*5*/
DROP TABLE T_SAV_DOCUMENTOS; /*2*/
DROP TABLE T_SAV_ENDERECO; /*3*/
DROP TABLE T_SAV_CONTATO; /*4*/
DROP TABLE T_SAV_SEGURO; /*9*/
DROP TABLE T_SAV_PEDAL_LEVE; /*6*/
DROP TABLE T_SAV_PEDAL_ESSENCIAL; /*7*/
DROP TABLE T_SAV_PEDAL_ELITE; /*8*/
DROP TABLE T_SAV_PAGAMENTO; /*14*/
DROP TABLE T_SAV_PIX; /*10*/
DROP TABLE T_SAV_BOLETO; /*11*/
DROP TABLE T_SAV_CARTAO_CREDITO; /*12*/
DROP TABLE T_SAV_CARTAO_DEBITO; /*13*/
DROP TABLE T_SAV_CLIENTE_PORTO; /*15*/
DROP TABLE T_SAV_VISTORIA; /*16*/
DROP TABLE T_SAV_CADASTRO_BICICLETA; /*22*/
DROP TABLE T_SAV_MODALIDADE; /*20*/
DROP TABLE T_SAV_ITENS_CUSTOMIZADOS; /*21*/
DROP TABLE T_SAV_MOUNTAIN_BIKE; /*17*/
DROP TABLE T_SAV_PERFORMANCE; /*18*/
DROP TABLE T_SAV_URBANA; /*19*/

